command:
  - "streamlit"
  - "run"
  - "app.py"
env:
  - name: "DATABRICKS_CATALOG"
    value: "db_ai_strike_team"
  - name: "DATABRICKS_SCHEMA"
    value: "sec_intelligence"
  - name: "DATABRICKS_VOLUME"
    value: "raw_filings"
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "58fc0be4c55c7e10"
  - name: "VECTOR_SEARCH_ENDPOINT"
    value: "sec_vs_endpoint"
  - name: "SERVING_ENDPOINT"
    value: "databricks-meta-llama-3-3-70b-instruct"
  - name: "STREAMLIT_GATHER_USAGE_STATS"
    value: "false"

